import "./globals.css";
import type { Metadata } from "next";
import { Roboto, Exo } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ['100', '300', '400', '500', '700', '900']
});
const exo = Exo({
  weight: ['300', '400', '700',],
  style: ['normal','italic'],
  subsets: ['latin'],
  display: 'swap',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={exo.className}>{children}</body>
    </html>
  );
}
